server:
  port: 8140

spring:
  application:
    name: config-client

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/,http://localhost:8110/eureka/
      
foo: 33333
